# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: KSPAssg_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- dev
- staging

variables:
  buildConfiguration: 'Release'
  osImage: 'windows-latest'

stages:
  - stage: 'Build_Stage'
    displayName: 'Build Stage'
    jobs:
      - job: 'build'
        steps:
        - task: DotNetCoreCLI@2
          displayName: 'Restoring Nuget Packages'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
            feedsToUse: 'select'
        - task: DotNetCoreCLI@2
          displayName: 'Building'
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(buildConfiguration)'
        - task: DotNetCoreCLI@2
          displayName: 'Publishing'
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '-c $(buildConfiguration) -o $(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'

  - stage: 'Development_Stage'
    dependsOn: Build_Stage
    displayName: 'Dev Deployment'
    jobs:
      - deployment: dev_agent
        pool:
          vmImage: 'windows-latest'
          environment: 
          name: dev
          resourceType: VirtualMachine
          strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadBuildArtifacts@1
                  inputs:
                    buildType: 'current'
                    downloadType: 'single'
                    artifactName: 'drop'
                    downloadPath: '$(System.ArtifactStagingDirectory)'
                - task: CopyFiles@2
                  inputs:
                    SourceFolder: '$(System.ArtifactStagingDirectory)'
                    Contents: '**'
                    TargetFolder: '%SystemDrive%\inetpub\wwwroot\KSPAssgProd'
                    CleanTargetFolder: true
                    OverWrite: true
          
